name: Build My App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf autotools-dev libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 kivy

      - name: Build APK with Buildozer
        run: |
          cd test_app
          buildozer -v android debug
        env:
          ACCEPT_SDK_LICENSE: "y"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: my-android-app
          path: test_app/bin/*.apk

